ci: update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,21 +12,25 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Pack up
-        run: zip -r build.zip build/
-      - name: Setup SSH
-        uses: shimataro/ssh-key-action@v2
+      - name: Login to Docker Registry
+        uses: docker/login-action@v3
         with:
-          key: ${{ secrets.SSH_KEY }}
-          known_hosts: unnecessary
-      - name: Deploy
+          registry: ${{ vars.DOCKER_HOST }}
+          username: ${{ vars.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v5
+        with:
+          push: true
+          context: .
+          file: Dockerfile
+          tags: ${{ vars.DOCKER_HOST }}/caiwen-blog-data:latest
+      - name: Webhook
         run: |
-          scp -o StrictHostKeyChecking=no build.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_DIR }}/data
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-          cd ${{ secrets.APP_DIR }}/data
-          docker-compose stop
-          rm -rf build
-          unzip build.zip
-          rm build.zip
-          docker-compose start
-          EOF
+          set -e
+          response=$(curl -s -w "%{http_code}" -o response_body.txt "${{ vars.WEBHOOK }}?token=${{ secrets.WEBHOOK_TOKEN }}")
+          cat response_body.txt
+          if [ "$response" != "200" ]; then
+            echo "Webhook failed with HTTP code $response"
+            exit 1
+          fi
